version: "3.8"

services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./media:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=${TA_HOST}
      - TA_USERNAME=${TA_USERNAME}
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${TA_ELASTIC_PASSWORD}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - main-network

  archivist-redis:
    container_name: archivist-redis
    image: redis:7
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es
    networks:
      - main-network

  archivist-es:
    container_name: archivist-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${TA_ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - main-network

networks:
  main-network:
    external: true
    name: docker_main-network
